indent.tail = [
  "element"
  "if_statement"
  "each_statement"
  "await_statement"
]

outdent.all = [
  "end_tag"
  "else_statement"
  "if_end_expr"
  "each_end_expr"
  "await_end_expr"
  ">"
  "/>"
]

ignore = "comment" 
