[indent]
all = [
 { parent_kind_in = ["assignment_expression", "compound_assignment_expr"], field_name_in = ["right"]},
 { parent_kind_in = ["let_declaration"], field_name_in = ["value"] }
]
tail = [
 "use_list",
 "block",
 "match_block",
 "arguments",
 "parameters",
 "declaration_list",
 "field_declaration_list",
 "field_initializer_list",
 "struct_pattern",
 "tuple_pattern",
 "unit_expression",
 "enum_variant_list",
 "call_expression",
 "binary_expression",
 "field_expression",
 "tuple_expression",
 "array_expression",
 "where_clause",
 "macro_invocation"
]

[outdent]
all = [
 "where",
 "}",
 "]",
 ")"
]
