[indent]
all = [
  # Indent non-grouped bodies of if-, while- and do-while-statements.
  # TODO Add indent for the for-statement (ideally the body of a for-statement should have a field name in the tree-sitter grammar)
  { kind_not_in = ["compound_statement"], parent_kind_in = ["if_statement", "while_statement", "do_statement"], field_name_in = ["consequence", "body"] }
]
tail = [
  "compound_statement",
  "field_declaration_list",
  "enumerator_list",
  "parameter_list",
  "init_declarator",
  "case_statement",
  "condition_clause",
  "expression_statement",
]

[outdent]
all = [
  "case",
  "access_specifier",
  "}",
  "]",
]
